/**
 * =============================================================================
 * TERMINOLOGY CONFIGURATION — SINGLE SOURCE OF TRUTH FOR ALL VISIBLE TEXT
 * =============================================================================
 *
 * No component may contain a hardcoded user-visible string. Every label,
 * heading, button caption, column title, empty-state sentence and help hint is
 * read from this dictionary.
 *
 * Alias comments mark terms the client is likely to rename during requirement
 * discussion. Renaming the value here updates every screen that uses it.
 *
 * English only.
 */

export const terminology = {
  // ===========================================================================
  common: {
    appTagline: 'Contractor Management System',
    demoBanner: 'Sample data — for requirement discussion only.',
    dismiss: 'Dismiss',
    loading: 'Loading…',
    save: 'Save',
    saveDraft: 'Save Draft',
    submit: 'Submit',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    edit: 'Edit',
    delete: 'Delete',
    remove: 'Remove',
    view: 'View',
    print: 'Print',
    download: 'Download',
    upload: 'Upload',
    search: 'Search',
    searchPlaceholder: 'Search documents, vendors, items…',
    filters: 'Filters',
    showFilters: 'Show Filters',
    hideFilters: 'Hide Filters',
    clearFilters: 'Clear All',
    clear: 'Clear',
    apply: 'Apply',
    reset: 'Reset',
    actions: 'Actions',
    addRow: 'Add Row',
    deleteRow: 'Delete Row',
    total: 'Total',
    subtotal: 'Sub Total',
    grandTotal: 'Grand Total',
    approve: 'Approve',
    reject: 'Reject',
    returnForCorrection: 'Return for Correction', // client may call this 'Send Back'
    revise: 'Revise',
    remarks: 'Remarks',
    remarksRequired: 'Remarks are mandatory for this action.',
    requiredField: 'This field is required.',
    optional: 'Optional',
    yes: 'Yes',
    no: 'No',
    all: 'All',
    none: 'None',
    selected: 'selected',
    rowsSelected: 'row(s) selected',
    of: 'of',
    page: 'Page',
    rowsPerPage: 'Rows per page',
    showing: 'Showing',
    to: 'to',
    entries: 'entries',
    noRecords: 'No records found',
    noRecordsHint: 'Adjust the filters above or create a new record to get started.',
    exportExcel: 'Export to Excel',
    exportPdf: 'Export to PDF',
    columns: 'Columns',
    columnVisibility: 'Show / hide columns',
    retry: 'Retry',
    errorTitle: 'Something went wrong',
    errorHint: 'The information could not be loaded. Please try again.',
    inPreparation: 'In preparation',
    inPreparationHint:
      'This screen is part of the agreed scope and will be built after the requirement discussion is signed off.',
    unsavedChanges: 'You have unsaved changes',
    unsavedChangesHint: 'If you leave this page now, the details you entered will be lost.',
    stayOnPage: 'Stay on this Page',
    discardChanges: 'Discard Changes',
    createdBy: 'Created By',
    createdOn: 'Created On',
    modifiedBy: 'Modified By',
    modifiedOn: 'Modified On',
    from: 'From',
    dateRange: 'Date Range',
    fromDate: 'From Date',
    toDate: 'To Date',
    status: 'Status',
    documentNo: 'Document No.', // client may call this 'Ref No.'
    date: 'Date',
    amount: 'Amount',
    quantity: 'Quantity',
    rate: 'Rate',
    unit: 'Unit',
    uom: 'UOM',
    description: 'Description',
    narration: 'Narration',
    attachments: 'Attachments',
    dragDropHint: 'Drag and drop files here, or click to browse',
    fileName: 'File Name',
    category: 'Category',
    uploadedBy: 'Uploaded By',
    uploadedOn: 'Uploaded On',
    expiryDate: 'Expiry Date',
    noAttachments: 'No documents attached',
    noAttachmentsHint: 'Attach supporting documents such as quotations, photographs or approvals.',
    currency: 'INR',
    currencySymbol: '₹',
    inLakh: 'Lakh',
    inCrore: 'Cr',
    helpTitle: 'What is this?',
    viewDetails: 'View Details',
    backToList: 'Back to List',
    selectPlaceholder: 'Select…',
    searchSelectPlaceholder: 'Type to search…',
    noOptions: 'No matching options',
    trendUp: 'up',
    trendDown: 'down',
    vsLastMonth: 'vs last month',
    drillDown: 'View breakdown',
  },

  // ===========================================================================
  nav: {
    home: 'Home',
    groupMasters: 'Masters',
    groupProjectControls: 'Project Controls',
    groupProcurement: 'Procurement',
    groupInventory: 'Stores & Inventory',
    groupSubcontract: 'Subcontractors',
    groupPlant: 'Plant & Fleet',
    groupHr: 'HR & Labour',
    groupDocuments: 'Documents',
    groupOrderBook: 'Order Book MIS',
    groupReports: 'Reports',
    groupHandover: 'Accounts Handover',
    groupAdministration: 'Administration',
    groupPortals: 'External Portals',
    collapseSidebar: 'Collapse menu',
    expandSidebar: 'Expand menu',
    notifications: 'Notifications',
    profile: 'My Profile',
    changePassword: 'Change Password',
    logout: 'Sign Out',
    company: 'Company',
    project: 'Project',
    site: 'Site',
    selectCompany: 'Select Company',
    selectProject: 'Select Project',
    allProjects: 'All Projects',
    showcase: 'Component Showcase',
  },

  // ===========================================================================
  masters: {
    companies: 'Companies',
    projects: 'Projects',
    sitesStores: 'Sites & Stores',
    departments: 'Departments',
    employees: 'Employees',
    vendors: 'Vendors', // client may call this 'Suppliers'
    subcontractors: 'Subcontractors',
    labourContractors: 'Labour Contractors', // client may call this 'Mistri / Petty Contractors'
    items: 'Items & Materials',
    uom: 'UOM',
    uomFull: 'Units of Measurement',
    hsnSac: 'HSN/SAC',
    equipment: 'Equipment & Vehicles',
    wbs: 'WBS / Cost Codes', // client may call this 'BOQ Heads' or 'Activity Codes'
    taxCategories: 'Tax Categories',
    documentCategories: 'Document Categories',

    companyName: 'Company Name',
    legalName: 'Legal Name',
    companyCode: 'Code',
    companyType: 'Entity Type',
    gstin: 'GSTIN',
    pan: 'PAN',
    cin: 'CIN',
    address: 'Address',
    city: 'City',
    state: 'State',
    pincode: 'PIN Code',
    contactPerson: 'Contact Person',
    phone: 'Phone',
    email: 'Email',

    projectCode: 'Project Code',
    projectName: 'Project Name',
    client: 'Client', // client may call this 'Employer'
    contractValue: 'Contract Value',
    projectType: 'Project Type',
    startDate: 'Start Date',
    endDate: 'Scheduled Completion',
    physicalProgress: 'Physical Progress',
    financialProgress: 'Financial Progress',
    chainageFrom: 'Chainage From',
    chainageTo: 'Chainage To',
    projectManager: 'Project Manager',
    location: 'Location',

    specification: 'Specification',
    stockUom: 'Stock UOM',
    reorderLevel: 'Reorder Level',

    gstRate: 'GST Rate',

    paymentTerms: 'Payment Terms',
    creditDays: 'Credit Days',
    msmeNo: 'MSME Registration No.',
    bankAccount: 'Bank Account No.',
    ifsc: 'IFSC Code',

    employeeCode: 'Employee Code',
    employeeName: 'Employee Name',
    designation: 'Designation',
    department: 'Department',
    dateOfJoining: 'Date of Joining',
    reportingTo: 'Reporting To',

    trade: 'Trade',
    siteName: 'Site / Store Name',
    siteType: 'Type',
    storeKeeper: 'Store Keeper',

    uomCode: 'UOM Code',
    uomName: 'Unit Name',
    uomCategory: 'Category',
    uomDecimals: 'Decimal Places',
    uomIsBase: 'Base Unit',
    uomConversions: 'Conversions',
    uomNew: 'New Unit',
    uomEdit: 'Edit Unit',
    uomSubtitle: 'Units in which materials are purchased, stored and issued.',
    uomEmpty: 'No units defined',
    uomEmptyHint: 'Add a unit such as MT, BAG or CUM to get started.',
    uomDuplicateCode: 'This code is already used by another unit.',
    uomDecimalsHint: '0 for countable items, 2 or 3 for weights and volumes.',
    uomBaseHint: 'The reference unit of its category — for example KG for weight.',
    activate: 'Activate',
    deactivate: 'Deactivate',
    activateConfirm: 'Make this record available for use again?',
    deactivateConfirm:
      'Existing records keep this value, but it will no longer appear in new entries.',
    catCOUNT: 'Count',
    catWEIGHT: 'Weight',
    catVOLUME: 'Volume',
    catLENGTH: 'Length',
    catAREA: 'Area',
    catTIME: 'Time',
    catOTHER: 'Other',

    hsnFull: 'HSN / SAC Master',
    hsnSubtitle: 'Tax classification codes used on purchase orders, invoices and bills.',
    hsnCode: 'Code',
    hsnKind: 'Type',
    hsnDescription: 'Description',
    hsnGstRate: 'GST %',
    hsnCgst: 'CGST %',
    hsnSgst: 'SGST %',
    hsnIgst: 'IGST %',
    hsnCess: 'Cess %',
    hsnEffectiveFrom: 'Effective From',
    hsnNonGst: 'Outside GST',
    hsnNew: 'New Code',
    hsnEdit: 'Edit Code',
    hsnEmpty: 'No codes defined',
    hsnEmptyHint: 'Add an HSN code for materials or a SAC code for services.',
    hsnDuplicateCode: 'This code already exists.',
    hsnSplitNote: 'CGST and SGST are half of the GST rate each. IGST equals the full rate.',
    hsnNonGstHint:
      'Tick for diesel, petrol and liquor — these are taxed under state VAT, not GST.',
    hsnKindHint: 'HSN for goods and materials. SAC for services such as hire or transport.',
    kindHSN: 'HSN (Goods)',
    kindSAC: 'SAC (Services)',

    itemFull: 'Item & Material Master',
    itemSubtitle: 'Every material, consumable, spare and service that is purchased, stored or issued.',
    itemNew: 'New Item',
    itemEdit: 'Edit Item',
    itemImport: 'Import Items',
    itemEmpty: 'No items defined',
    itemEmptyHint: 'Add an item such as OPC 53 Cement or TMT Bar 12mm to get started.',
    itemDuplicateCode: 'This item code is already in use.',

    itemCode: 'Item Code',
    itemName: 'Item Name',
    itemGroup: 'Item Group',

    secIdentification: 'Identification',
    secClassification: 'Type & Behaviour',
    secUnits: 'Units & Conversion',
    secStock: 'Stock Control',
    secCosting: 'Costing Reference',

    itemShortName: 'Short Name',
    itemSubGroup: 'Sub Group',
    itemOldCode: 'Old / Legacy Code',
    itemBrand: 'Preferred Brand',
    itemMakeGrade: 'Make / Grade',
    itemType: 'Item Type',
    itemReturnable: 'Returnable',
    itemProduced: 'Produced In-house',
    itemBatchTracked: 'Batch Tracked',
    itemSerialTracked: 'Serial Numbered',
    itemRequiresQc: 'Requires Inspection',
    itemShelfLife: 'Shelf Life (Days)',
    itemHazardous: 'Hazardous',

    purchaseUom: 'Purchase UOM',
    purchaseFactor: 'Purchase to Stock Factor',
    issueUom: 'Issue UOM',
    issueFactor: 'Issue to Stock Factor',
    factorHint: '1 purchase unit equals how many stock units. 1 BAG = 50 KG.',

    minStock: 'Minimum Stock',
    maxStock: 'Maximum Stock',
    leadTime: 'Lead Time (Days)',
    allowNegative: 'Allow Negative Stock',
    defaultStore: 'Default Store',
    binLocation: 'Bin / Rack',

    valuationMethod: 'Valuation Method',
    standardRate: 'Standard Rate',
    lastPurchaseRate: 'Last Purchase Rate',
    lastPurchaseDate: 'Last Purchase Date',
    budgetRate: 'Budget Rate Reference',

    typeMATERIAL: 'Material',
    typeCONSUMABLE: 'Consumable',
    typeSPARE: 'Spare Part',
    typeFUEL: 'Fuel & Lubricant',
    typeRETURNABLE: 'Returnable',
    typePRODUCED: 'Produced',
    typeSERVICE: 'Service',
    typeASSET: 'Capital Asset',

    valWEIGHTED_AVERAGE: 'Weighted Average',
    valFIFO: 'FIFO',
    valSTANDARD: 'Standard Rate',

    grpCEMENT: 'Cement',
    grpSTEEL: 'Steel',
    grpAGGREGATE: 'Aggregate',
    grpSAND: 'Sand',
    grpGRANULAR: 'Granular Sub-base',
    grpBITUMEN: 'Bitumen',
    grpRMC: 'Ready Mix Concrete',
    grpMASONRY: 'Masonry',
    grpSHUTTERING: 'Shuttering & Staging',
    grpCONSUMABLE: 'Consumables',
    grpFUEL: 'Fuel',
    grpADMIXTURE: 'Admixtures',
    grpPIPES_FITTINGS: 'Pipes & Fittings',
    grpELECTRICAL: 'Electrical',
    grpSAFETY: 'Safety',
    isCapitalItem: 'Capital Item / Asset',

    vendorFull: 'Vendor & Supplier Master',
    vendorSubtitle: 'Every supplier, hire vendor and transporter you raise a purchase order or hire bill against.',
    vendorNew: 'New Vendor',
    vendorEdit: 'Edit Vendor',
    vendorEmpty: 'No vendors defined',
    vendorEmptyHint: 'Add a supplier such as a cement agency or stone crusher to get started.',
    vendorDuplicateCode: 'This vendor code is already in use.',
    vendorDuplicateGstin: 'A vendor with this GSTIN already exists.',

    secVendorIdentity: 'Identity & Category',
    secVendorTax: 'Tax Registration',
    secVendorContact: 'Address & Contact',
    secVendorCommercial: 'Payment Terms',
    secVendorBank: 'Bank Details',

    vendorCode: 'Vendor Code',
    vendorName: 'Vendor Name',
    vendorCategory: 'Supply Category',
    vendorGstin: 'GSTIN',
    vendorPan: 'PAN',
    vendorMsme: 'MSME / Udyam Number',
    vendorAddress: 'Address',
    vendorCity: 'City',
    vendorState: 'State',
    vendorContactPerson: 'Contact Person',
    vendorPhone: 'Phone',
    vendorEmail: 'Email',
    vendorPaymentTerms: 'Payment Terms',
    vendorCreditDays: 'Credit Days',
    vendorBankAccount: 'Bank Account Number',
    vendorIfsc: 'IFSC Code',

    catCEMENT: 'Cement',
    catSTEEL: 'Steel',
    catAGGREGATE: 'Aggregate',
    catBITUMEN: 'Bitumen',
    catDIESEL: 'Diesel & Lubricants',
    catHARDWARE: 'Hardware',
    catEQUIPMENT_HIRE: 'Equipment Hire',
    catTRANSPORT: 'Transport',
    catELECTRICAL: 'Electrical',
    catRMC: 'Ready Mix Concrete',

    subFull: 'Subcontractor Master',
    subSubtitle: 'Agencies executing work at site against work orders and measured bills.',
    subNew: 'New Subcontractor',
    subEdit: 'Edit Subcontractor',
    subEmpty: 'No subcontractors defined',
    subEmptyHint: 'Add an agency such as an earthwork or shuttering contractor to get started.',
    subDuplicateCode: 'This subcontractor code is already in use.',
    subDuplicateGstin: 'A subcontractor with this GSTIN already exists.',
    subCode: 'Subcontractor Code',
    subName: 'Agency Name',
    subIsLabour: 'Labour Contractor',
    subLicenceNo: 'Labour Licence No.',
    subLicenceRequired: 'Labour licence number is required for a labour contractor.',
    subLicenceOrphan: 'Tick Labour Contractor, or clear the licence number.',

    labourFull: 'Labour Contractor Master',
    labourSubtitle: 'Agencies supplying labour on a muster-roll basis, tracked for licence compliance.',
    labourNew: 'New Labour Contractor',
    labourEmpty: 'No labour contractors defined',
    labourEmptyHint: 'Labour contractors are subcontractors with a labour licence on record.',

    secSubIdentity: 'Identification',
    secSubTax: 'Tax Registration',
    secSubContact: 'Contact',
    secSubCompliance: 'Labour Compliance',

    trdEARTHWORK: 'Earthwork',
    trdSHUTTERING: 'Shuttering & Staging',
    trdBAR_BENDING: 'Bar Bending',
    trdCONCRETING: 'Concreting',
    trdBLOCKWORK_PLASTER: 'Blockwork & Plastering',
    trdBITUMINOUS: 'Bituminous Work',
    trdELECTRICAL: 'Electrical',
    trdPLUMBING: 'Plumbing',

    cmpFull: 'Company Master',
    cmpSubtitle: 'Legal entities that own projects — the parent company, SPVs and joint ventures.',
    cmpNew: 'New Company',
    cmpEdit: 'Edit Company',
    cmpEmpty: 'No companies defined',
    cmpEmptyHint: 'Every project belongs to a company, so at least one entity is needed here.',
    cmpDuplicateCode: 'This company code is already in use.',
    cmpDuplicateGstin: 'A company with this GSTIN already exists.',
    cmpCode: 'Company Code',
    cmpName: 'Company Name',
    cmpLegalName: 'Registered Legal Name',
    cmpType: 'Entity Type',
    cmpCin: 'CIN',
    cmpPincode: 'PIN Code',
    cmpDeactivateWarning:
      'Projects, sites and employees are linked to this company. Deactivating hides it from new entries but leaves existing records untouched.',

    secCmpIdentity: 'Entity',
    secCmpTax: 'Statutory Registration',
    secCmpAddress: 'Registered Address',
    secCmpContact: 'Contact',

    entPARENT: 'Parent Company',
    entSPV: 'Special Purpose Vehicle',
    entJV: 'Joint Venture',

        depFull: 'Department Master',
    depSubtitle: 'Functional departments used for routing approvals and grouping employees.',
    depNew: 'New Department',
    depEdit: 'Edit Department',
    depEmpty: 'No departments defined',
    depEmptyHint: 'Departments group employees and decide who approves what, so at least one is needed.',
    depDuplicateCode: 'This department code is already in use.',
    depDuplicateName: 'A department with this name already exists.',
    depCode: 'Department Code',
    depName: 'Department Name',
    depHead: 'Department Head',
    depHeadNone: 'Not assigned',
    depHeadHint: 'By convention the head is an employee already posted to this department.',
    depHeadOtherDept: 'This employee is currently posted to {dept}.',
    depDeactivateWarning:
      'Employees are linked to this department. Deactivating hides it from new entries but leaves existing records untouched.',

    secDepIdentity: 'Department',
    secDepOwner: 'Ownership',

    empFull: 'Employee Master',
    empSubtitle: 'People on the rolls, their posting and their reporting line.',
    empNew: 'New Employee',
    empEdit: 'Edit Employee',
    empEmpty: 'No employees defined',
    empEmptyHint: 'Employees raise and approve documents, so at least one record is needed.',
    empDuplicateCode: 'This employee code is already in use.',
    empDuplicateEmail: 'An employee with this email already exists.',
    empCode: 'Employee Code',
    empName: 'Employee Name',
    empDesignation: 'Designation',
    empDoj: 'Date of Joining',
    empReportingTo: 'Reports To',
    empReportingNone: 'No reporting manager',
    empReportingSelf: 'An employee cannot report to themselves.',
    empReportingCycle: 'This creates a reporting loop: {chain}.',
    empReportingCrossCompany: 'Manager is in {company}. Cross-company reporting is allowed.',
    empPf: 'PF Number',
    empEsi: 'ESI Number',
    empPosting: 'Posting',
    empProjectNone: 'Head office / no project',
    empProjectCompanyMismatch: 'This project belongs to {company}.',
    empDeactivateWarning:
      'Documents raised by this employee stay on record. Deactivating removes them from approver and assignment lists.',

    secEmpIdentity: 'Identification',
    secEmpPosting: 'Posting & Reporting',
    secEmpStatutory: 'Statutory',
    secEmpContact: 'Contact',
    company: 'Company',
    project: 'Project',

    prjFull: 'Project Master',
    prjSubtitle: 'Contracts under execution — the cost centre every document belongs to.',
    prjNew: 'New Project',
    prjEdit: 'Edit Project',
    prjEmpty: 'No projects defined',
    prjEmptyHint: 'Every indent, purchase order and bill belongs to a project, so at least one is needed.',
    prjDuplicateCode: 'This project code is already in use.',
    prjCode: 'Project Code',
    prjName: 'Full Project Name',
    prjShortName: 'Short Name',
    prjType: 'Project Type',
    prjClient: 'Client / Employer',
    prjLocation: 'Location',
    prjContractValue: 'Contract Value',
    prjContractValueCr: 'Contract Value (₹ Cr)',
    prjStartDate: 'Commencement Date',
    prjEndDate: 'Scheduled Completion',
    prjManager: 'Project Manager',
    prjChainageFrom: 'Chainage From',
    prjChainageTo: 'Chainage To',
    prjChainageOrder: 'Chainage To must be beyond Chainage From.',
    prjChainagePair: 'Enter both chainage points, or neither.',
    prjPhysicalProgress: 'Physical Progress',
    prjFinancialProgress: 'Financial Progress',
    prjProgressNote: 'Maintained from daily progress reports — not editable here.',
    prjEndBeforeStart: 'Completion date must be after the commencement date.',
    prjManagerOtherCompany: 'This manager is posted to {company}.',
    prjStatus: 'Project Status',

    secPrjIdentity: 'Project',
    secPrjContract: 'Contract',
    secPrjSchedule: 'Schedule',
    secPrjLinear: 'Chainage',
    secPrjProgress: 'Progress',

    prjACTIVE: 'Active',
    prjCOMPLETED: 'Completed',
    prjON_HOLD: 'On Hold',

    ptROAD: 'Road',
    ptBRIDGE: 'Bridge / Structure',
    ptINDUSTRIAL_PARK: 'Industrial Park',
    ptWAREHOUSE: 'Warehouse',
    ptBUILDING: 'Building',

    sitFull: 'Site & Store Master',
    sitSubtitle: 'Physical locations where material is received, stored, issued or produced.',
    sitNew: 'New Site / Store',
    sitEdit: 'Edit Site / Store',
    sitEmpty: 'No sites or stores defined',
    sitEmptyHint: 'Every receipt and issue happens at a store, so at least one is needed.',
    sitDuplicateCode: 'This site code is already in use.',
    sitCode: 'Site / Store Code',
    sitIsStore: 'Holds Stock',
    sitIsStoreForced: 'A main store or site store always holds stock.',
    sitStoreKeeperOrphan: 'Tick Holds Stock, or clear the store keeper.',
    sitStoreKeeperNone: 'Not assigned',
    sitProjectRequired: 'A site store, plant or site office belongs to a project.',
    sitProjectOnMain: 'A main store serves every project, so leave the project blank.',
    sitProjectCompanyMismatch: 'This project belongs to {company}.',
    sitProjectNone: 'Company level / no project',
    sitDeactivateWarning:
      'Stock balances and documents at this location stay on record. Deactivating removes it from new entries.',

    secSitIdentity: 'Identification',
    secSitOwnership: 'Company & Project',
    secSitStock: 'Stock Handling',

    stMAIN_STORE: 'Main Store',
    stSITE_STORE: 'Site Store',
    stSITE_OFFICE: 'Site Office',
    stPLANT: 'Plant / Yard',

    eqpFull: 'Equipment & Vehicle Master',
    eqpSubtitle: 'Owned and hired plant, vehicles and gensets, with deployment and service position.',
    eqpNew: 'New Equipment',
    eqpEdit: 'Edit Equipment',
    eqpEmpty: 'No equipment defined',
    eqpEmptyHint: 'Log books, fuel issues and maintenance all post against an equipment record.',
    eqpDuplicateCode: 'This equipment code is already in use.',
    eqpDuplicateReg: 'This registration number is already recorded.',
    eqpCode: 'Equipment Code',
    eqpName: 'Description',
    eqpType: 'Equipment Type',
    eqpRegNo: 'Registration No.',
    eqpOwnership: 'Ownership',
    eqpHireVendor: 'Hire Vendor',
    eqpHireRate: 'Hire Rate',
    eqpHireRateUnit: 'Rate Per',
    eqpOperator: 'Operator',
    eqpOperatorNone: 'Not assigned',
    eqpStatus: 'Operational Status',
    eqpCurrentHmr: 'Current Reading',
    eqpCurrentHmrHint: 'Hour meter for plant, odometer reading for vehicles.',
    eqpNextServiceHmr: 'Next Service Due At',
    eqpNextServiceDate: 'Next Service Due On',
    eqpServiceOverdue: 'Service overdue',
    eqpHireFieldsRequired: 'Hire vendor and rate are required for hired equipment.',
    eqpHireFieldsOwned: 'Hire details apply to hired equipment only.',
    eqpRegNoHint: 'Road-registered vehicles only. Plant and gensets have none.',
    eqpDeactivateWarning:
      'Log books, fuel and maintenance history stay on record. Deactivating removes it from new entries. Use Operational Status for a breakdown.',

    secEqpIdentity: 'Identification',
    secEqpOwnership: 'Ownership & Hire',
    secEqpDeployment: 'Deployment',
    secEqpService: 'Reading & Service',

    eoOWNED: 'Owned',
    eoHIRED: 'Hired',
    esWORKING: 'Working',
    esIDLE: 'Idle',
    esBREAKDOWN: 'Breakdown',
    esUNDER_MAINTENANCE: 'Under Maintenance',

    wbsFull: 'Work Breakdown Structure',
    wbsSubtitle: 'Cost codes a project is planned, measured and billed against.',
    wbsNew: 'New WBS Node',
    wbsEdit: 'Edit WBS Node',
    wbsChild: 'Add Child Node',
    wbsEmpty: 'No WBS defined for this project',
    wbsEmptyHint: 'Measurements, budgets and cost reports all post against a WBS code.',
    wbsSelectProject: 'Select a project to view its work breakdown.',
    wbsDuplicateCode: 'This code is already used in this project.',
    wbsCode: 'WBS Code',
    wbsName: 'Description',
    wbsParent: 'Parent Node',
    wbsParentNone: 'Top level',
    wbsLevel: 'Level',
    wbsBudgetedQty: 'Budgeted Qty',
    wbsBudgetedCost: 'Budgeted Cost',
    wbsExecutedQty: 'Executed Qty',
    wbsActualCost: 'Actual Cost',
    wbsVariance: 'Variance',
    wbsExecutionReadOnly: 'Maintained from measurement books — not editable here.',
    wbsParentCycle: 'A node cannot be its own parent or descendant.',
    wbsParentCrossProject: 'The parent must belong to the same project.',
    wbsHasChildren: 'This node has child nodes. Budget is normally entered at the lowest level.',
    wbsDeactivateWarning:
      'Measurements and costs already booked stay on record. Deactivating removes the code from new entries.',

    secWbsIdentity: 'Identification',
    secWbsBudget: 'Budget',
    secWbsExecution: 'Execution',

  },

  // ===========================================================================
  project: {
    dashboard: 'Project Dashboard',
    contractSummary: 'Contract Summary',
    wbsBudget: 'WBS & Budget',
    dpr: 'Daily Progress Report', // client may call this 'DPR' or 'Site Report'
    dprShort: 'DPR',
    hindranceRegister: 'Hindrance Register', // client may call this 'Delay Register'
    variationRegister: 'Variation Register', // client may call this 'EOT / Extra Items'
    claimRegister: 'Claim Register',
    bgRetention: 'BG & Retention Register', // Bank Guarantee & Retention Money
    orderBook: 'Order Book',
    projectSalesMis: 'Project Sales MIS',

    budgetedQty: 'Budgeted Quantity',
    executedQty: 'Executed Quantity',
    balanceQty: 'Balance Quantity',
    budgetedCost: 'Budgeted Cost',
    actualCost: 'Actual Cost',
    costVariance: 'Cost Variance',
    workDone: 'Work Done',
    manpowerDeployed: 'Manpower Deployed',
    weather: 'Weather',
    hindranceReason: 'Reason for Hindrance',
    bgNumber: 'BG Number',
    bgType: 'BG Type',
    bgAmount: 'BG Amount',
    validUpto: 'Valid Upto',
    retentionHeld: 'Retention Held',
    wbsBudgetSubtitle: 'Budget against actual cost for every work item, totalled up the bill.',
    wbsRolledNote: 'Heading rows total the items beneath them. Only the lowest-level items carry their own budget.',
    wbsOwnBudget: 'Budget',
    wbsSpent: 'Actual',
    wbsBalance: 'Balance',
    wbsConsumed: 'Consumed',
    wbsPhysical: 'Executed',
    wbsKpiBudget: 'Sanctioned Budget',
    wbsKpiActual: 'Actual Cost',
    wbsKpiBalance: 'Balance Available',
    wbsKpiOverrun: 'Items Over Budget',
    wbsOverrunHint: 'Cost running ahead of physical progress',
    wbsBudgetEmpty: 'No work items for this project',
    wbsBudgetEmptyHint: 'Add items in the WBS master to see the budget.',
    selectProject: 'Project',

        dprSubtitle: 'What was done at site each day — quantities, manpower, machinery and hold-ups.',
    dprNew: 'New Daily Progress Report',
    dprEmpty: 'No daily progress reports',
    dprEmptyHint: 'Site engineers record the day’s work here each evening.',
    dprPreparedBy: 'Prepared By',
    dprActivities: 'Activities',
    dprLabourTotal: 'Manpower',
    dprEquipmentTotal: 'Machines',
    dprHoursLost: 'Hours Lost',
    dprRainfall: 'Rainfall (mm)',
    dprSafety: 'Safety Incidents',
    dprHindrance: 'Hindrance',
    dprGeneralRemarks: 'General Remarks',
    dprNoHindrance: 'No hindrance reported',
    dprTodayQty: 'Today',
    dprCumulativeQty: 'Cumulative',
    dprLocation: 'Location / Chainage',
    dprSkilled: 'Skilled',
    dprUnskilled: 'Unskilled',
    dprOwnLabour: 'Own muster',
    dprHoursWorked: 'Worked',
    dprIdleHours: 'Idle',
    dprBreakdownHours: 'Breakdown',
    dprDiesel: 'Diesel (L)',
    dprKpiReports: 'Reports This Month',
    dprKpiPending: 'Awaiting Approval',
    dprKpiHoursLost: 'Hours Lost This Month',
    dprKpiManpower: 'Manpower Last Report',
    secDprProgress: 'Work Done',
    secDprLabour: 'Manpower Deployed',
    secDprEquipment: 'Plant & Machinery',
    secDprConditions: 'Site Conditions',
    wthCLEAR: 'Clear',
    wthCLOUDY: 'Cloudy',
    wthLIGHT_RAIN: 'Light Rain',
    wthHEAVY_RAIN: 'Heavy Rain',
    wthEXTREME_HEAT: 'Extreme Heat',

    hindranceSubtitle: 'Events that held up work, who was responsible, and the time claimed against each.',
    hindranceNew: 'Record Hindrance',
    hindranceEdit: 'Edit Hindrance',
    hindranceEmpty: 'No hindrances recorded',
    hindranceEmptyHint: 'Record delays caused by land, drawings, utilities, permissions or weather.',
    hinFrom: 'From',
    hinTo: 'To',
    hinOngoing: 'Ongoing',
    hinCategory: 'Cause',
    hinResponsibility: 'Responsibility',
    hinDescription: 'What happened',
    hinActivity: 'Activity Affected',
    hinLocation: 'Location / Chainage',
    hinWorkStopped: 'Work fully stopped',
    hinWorkSlowed: 'Work slowed',
    hinDaysLost: 'Days',
    hinEotClaimable: 'Claimable as extension of time',
    hinEotDays: 'EOT Days Claimed',
    hinActionTaken: 'Action Taken',
    hinResolved: 'Resolution',
    hinKpiTotal: 'Hindrances Recorded',
    hinKpiOpen: 'Still Open',
    hinKpiDaysOpen: 'Open Days Accumulated',
    hinKpiEot: 'EOT Days Claimed',
    hinEotHint: 'Across all claimable hindrances',
    hinDescriptionRequired: 'Describe what held up the work.',
    hinToBeforeFrom: 'The closing date cannot be before the start date.',
    hinEotWithoutClaim: 'Enter the days being claimed, or untick the claim box.',
    secHinEvent: 'The Event',
    secHinImpact: 'Impact',
    secHinFollowUp: 'Follow-up',
    hcLAND_ACQUISITION: 'Land not handed over',
    hcDRAWINGS_APPROVAL: 'Drawings or approvals awaited',
    hcUTILITY_SHIFTING: 'Utility shifting pending',
    hcSTATUTORY_PERMISSION: 'Statutory permission pending',
    hcWEATHER: 'Weather',
    hcCLIENT_MATERIAL: 'Client-supplied material',
    hcPAYMENT_DELAY: 'Payment delay',
    hcLABOUR_SHORTAGE: 'Labour shortage',
    hcEQUIPMENT_BREAKDOWN: 'Equipment breakdown',
    hcLAW_AND_ORDER: 'Law and order',
    hcOTHER: 'Other',
    hrCLIENT: 'Client',
    hrCONTRACTOR: 'Own',
    hrEXTERNAL: 'External',

        variationRegisterFull: 'Variation & Deviation Register',
    variationSubtitle:
      'Extra items, quantity deviations and design changes, with what has been claimed against what the client has admitted.',
    variationNew: 'Record Variation',
    variationEdit: 'Edit Variation',
    variationEmpty: 'No variations recorded',
    variationEmptyHint:
      'Record extra items, quantity deviations and design changes so the claim position stays visible.',
    varDate: 'Date',
    varNo: 'Variation No.',
    varCategory: 'Nature',
    varOrigin: 'Raised Under',
    varDescription: 'Description',
    varActivity: 'BOQ Item',
    varLocation: 'Location / Chainage',
    varQty: 'Quantity',
    varUom: 'Unit',
    varRate: 'Rate',
    varProposed: 'Claimed',
    varApproved: 'Admitted',
    varShortfall: 'Not Admitted',
    varUndecided: 'With client',
    varClientRef: 'Client Reference',
    varClientRefDate: 'Reference Date',
    varRateAnalysis: 'Needs fresh rate analysis',
    varTimeExtension: 'Time Extension Sought (days)',
    varRemarks: 'Remarks',
    varKpiTotal: 'Variations Raised',
    varKpiApproved: 'Value Admitted',
    varKpiPending: 'Value With Client',
    varKpiDeviation: 'Deviation on Contract',
    varDeviationHint: 'Admitted value as a share of the agreement value',
    varPendingHint: 'Awaiting a client decision',
    varDescriptionRequired: 'Describe the variation and why it arose.',
    varAmountRequired: 'Enter the value being claimed.',
    varApprovedWithoutDecision: 'An admitted value applies only once the variation is approved or rejected.',
    secVarEvent: 'The Variation',
    secVarValue: 'Valuation',
    secVarClient: 'Client Position',
    vcEXTRA_ITEM: 'Extra Item',
    vcDEVIATION_QTY: 'Quantity Deviation',
    vcSUBSTITUTED_ITEM: 'Substituted Item',
    vcDESIGN_CHANGE: 'Design Change',
    vcSCOPE_ADDITION: 'Addition to Scope',
    vcOMISSION: 'Omission',
    voCLIENT_INSTRUCTION: 'Client Instruction',
    voSITE_CONDITION: 'Site Condition',
    voDESIGN_REVISION: 'Design Revision',
    voSTATUTORY: 'Statutory Requirement',
    voCONTRACTOR_PROPOSAL: 'Contractor Proposal',

    claimRegisterFull: 'Claim Register',
    claimSubtitle:
      'Claims on the client for time and money, from the first notice through to settlement.',
    claimNew: 'Record Claim',
    claimEdit: 'Edit Claim',
    claimEmpty: 'No claims recorded',
    claimEmptyHint:
      'Record notices and claims for extension of time, prolongation, idling and escalation so nothing lapses for want of notice.',
    clmDate: 'Date',
    clmNo: 'Claim No.',
    clmType: 'Claim Type',
    clmStage: 'Stage',
    clmTitle: 'Claim',
    clmDescription: 'Basis of Claim',
    clmHindrance: 'Arising From',
    clmVariation: 'Related Variation',
    clmNoticeDate: 'Notice Date',
    clmNoticeRef: 'Notice Reference',
    clmParticularsDate: 'Particulars Submitted',
    clmParticularsLag: 'Notice to Particulars',
    clmClaimed: 'Amount Claimed',
    clmSettled: 'Amount Settled',
    clmShortfall: 'Not Allowed',
    clmClaimedDays: 'Days Claimed',
    clmSettledDays: 'Days Allowed',
    clmSettledDate: 'Settlement Date',
    clmIsSettled: 'Settled or withdrawn',
    clmRemarks: 'Remarks',
    clmPending: 'Under consideration',
    clmDays: 'days',
    clmKpiTotal: 'Claims Raised',
    clmKpiLive: 'Value Being Pursued',
    clmKpiSettled: 'Value Settled',
    clmKpiDispute: 'In Conciliation or Arbitration',
    clmLiveHint: 'Excludes settled and withdrawn claims',
    clmDaysHint: 'Extension sought on live claims',
    clmTitleRequired: 'Give the claim a short title.',
    clmDescriptionRequired: 'Set out the basis of the claim.',
    clmSettledWithoutStage: 'A settled figure applies only once the claim is settled or withdrawn.',
    clmParticularsBeforeNotice: 'Particulars cannot be submitted before the notice date.',
    secClmEvent: 'The Claim',
    secClmNotice: 'Notice & Particulars',
    secClmValue: 'Amount & Time',
    secClmOutcome: 'Outcome',
    ctEOT: 'Extension of Time',
    ctPROLONGATION: 'Prolongation Cost',
    ctIDLE_RESOURCES: 'Idle Plant & Labour',
    ctPRICE_ESCALATION: 'Price Escalation',
    ctDELAYED_PAYMENT_INTEREST: 'Interest on Delayed Payment',
    ctCHANGE_IN_LAW: 'Change in Law',
    ctOTHER: 'Other',
    csNOTICE_GIVEN: 'Notice Given',
    csPARTICULARS_SUBMITTED: 'Particulars Submitted',
    csUNDER_REVIEW: 'Under Review',
    csENGINEER_DECISION: 'With the Engineer',
    csCONCILIATION: 'Conciliation',
    csARBITRATION: 'Arbitration',
    csSETTLED: 'Settled',
    csWITHDRAWN: 'Withdrawn',

    contractSummarySubtitle: 'Agreement value reconciled to the anticipated final value',
    cpStatementTitle: 'Contract statement',
    cpStatementNote:
      'Figures above the revised contract value are admitted by the client. Figures below it are still being pursued and should not be treated as earned.',

    cpParticulars: 'Particulars',
    cpAmount: 'Amount',
    cpBasis: 'Basis',

    cpAgreementValue: 'Agreement value',
    cpAgreementNote: 'As per letter of award',
    cpVariationsApproved: 'Add: variations admitted',
    cpRevisedValue: 'Revised contract value',
    cpRevisedNote: 'Admitted position',
    cpVariationsPending: 'Add: variations pending decision',
    cpClaimsLive: 'Add: claims under pursuit',
    cpAnticipatedValue: 'Anticipated final value',
    cpAnticipatedNote: 'If every pending item is admitted in full',
    cpOrders: 'orders',
    cpAwaiting: 'awaiting decision',
    cpUnderPursuit: 'live',

    cpKpiRevised: 'Revised contract value',
    cpKpiExposure: 'Under pursuit',
    cpKpiExposureHint: 'Variations pending plus live claims',
    cpKpiDeviation: 'Deviation admitted',
    cpKpiDeviationHint: 'Admitted variations as a share of the agreement value',
    cpDeviationBreach: 'Beyond the deviation limit — fresh sanction needed',
    cpKpiSettled: 'Claims settled',

    cpTimeTitle: 'Time position',
    cpKpiOriginalEnd: 'Original completion',
    cpKpiEotGranted: 'Extension granted',
    cpKpiEotSought: 'Extension sought',
    cpKpiRevisedEnd: 'Revised completion',
    cpDays: 'days',
    cpEotRegisterHint: 'days flagged on the hindrance register',
    cpEotGrantedHint: 'Granted on settled claims',
    cpOverdue: 'Date already passed',
    cpDaysRemaining: 'days remaining',

    cpProgressTitle: 'Execution position',
    cpKpiPhysical: 'Physical progress',
    cpKpiFinancial: 'Financial progress',
    cpKpiCost: 'Cost incurred',
    cpKpiCostHint: 'Against WBS budget',

    cpEmpty: 'No contract data for this project',
    cpEmptyHint: 'Check that the project has an agreement value and a WBS.',

    bgRetentionFull: 'Bank Guarantee & Retention Register',
    bgRetentionSubtitle:
      'Guarantees issued in the client’s favour and retention money held, with what falls due for extension.',
    bgTabGuarantees: 'Bank Guarantees',
    bgTabRetention: 'Retention Money',

    bgNew: 'Record Guarantee',
    bgEdit: 'Edit Guarantee',
    bgEmpty: 'No guarantees recorded',
    bgEmptyHint:
      'Record performance, mobilisation and retention guarantees so none lapses for want of extension.',
    bgRegisterNo: 'Register No.',
    bgIssueDate: 'Issued On',
    bgBank: 'Bank',
    bgBranch: 'Branch',
    bgBeneficiary: 'In Favour Of',
    bgStatusLabel: 'Position',
    bgClaimPeriod: 'Claim Period Upto',
    bgDaysToExpiry: 'Expires In',
    bgLapsed: 'Validity lapsed',
    bgExpiringSoon: 'Extension due',
    bgMarginPct: 'Margin %',
    bgMarginAmount: 'Margin / FDR Held',
    bgFdrNo: 'FDR Number',
    bgCommission: 'Commission % p.a.',
    bgPurpose: 'Purpose',
    bgReleasedOn: 'Released On',
    bgRemarks: 'Remarks',
    bgDays: 'days',
    bgKpiLive: 'Guarantees Live',
    bgKpiValue: 'Value Outstanding',
    bgKpiExpiring: 'Falling Due',
    bgKpiExpiringHint: 'Live guarantees expiring within 60 days',
    bgKpiMargin: 'Margin Money Locked',
    bgKpiMarginHint: 'Deposits and FDRs held by the bank',
    bgLapsedWarning: 'guarantee(s) already past validity',
    bgNumberRequired: 'Enter the number printed on the guarantee.',
    bgBankRequired: 'Enter the issuing bank.',
    bgBeneficiaryRequired: 'Enter who the guarantee is in favour of.',
    bgAmountRequired: 'Enter the guaranteed amount.',
    bgValidBeforeIssue: 'Validity cannot end before the date of issue.',
    bgClaimBeforeValid: 'The claim period runs beyond the validity date.',
    bgReleasedWithoutStatus: 'A release date applies only once the guarantee is released.',
    secBgInstrument: 'The Guarantee',
    secBgValidity: 'Validity',
    secBgBankTerms: 'Margin & Charges',
    secBgOutcome: 'Release',

    bgtPERFORMANCE: 'Performance Guarantee',
    bgtMOBILISATION_ADVANCE: 'Mobilisation Advance',
    bgtRETENTION_MONEY: 'Retention Money',
    bgtADVANCE_PAYMENT: 'Advance Payment',
    bgtSECURITY_DEPOSIT: 'Security Deposit',
    bgtEMD: 'Earnest Money',
    bgsLIVE: 'Live',
    bgsUNDER_EXTENSION: 'Under Extension',
    bgsEXPIRED: 'Expired',
    bgsRELEASED: 'Released',
    bgsINVOKED: 'Invoked',

    retSubtitle: 'Retention deducted from running account bills, and how it has been discharged.',
    retEmpty: 'No retention movements',
    retEmptyHint: 'Retention entries arise from running account bills.',
    retReadOnlyNote:
      'Maintained from running account bills — entries cannot be added here.',
    retDate: 'Date',
    retEvent: 'Movement',
    retBillNo: 'Bill',
    retBillAmount: 'Bill Value',
    retPct: 'Rate',
    retAmount: 'Amount',
    retBalance: 'Balance Held',
    retAgainstBg: 'Against Guarantee',
    retKpiDeducted: 'Total Deducted',
    retKpiReleased: 'Released',
    retKpiSubstituted: 'Covered by Guarantee',
    retKpiBalance: 'Retention Held',
    retKpiBalanceHint: 'Cash still with the client',
    reDEDUCTED: 'Deducted',
    reRELEASED: 'Released',
    reSUBSTITUTED_BY_BG: 'Substituted by BG',

    dashboardSubtitle: 'Time, progress, cost and commercial position for the selected project',
    dbAsOn: 'As on',

    dbSecProgress: 'Progress against programme',
    dbTimeElapsed: 'Time Elapsed',
    dbPhysical: 'Physical Progress',
    dbFinancial: 'Financial Progress',
    dbSlippage: 'Slippage',
    dbSlippageAhead: 'Ahead of programme',
    dbSlippageBehind: 'Behind programme',
    dbSlippageHint: 'Physical progress measured against time elapsed',
    dbDaysRemaining: 'Days Remaining',
    dbDaysOverrun: 'Days Overrun',
    dbOfDays: 'of',

    dbSecCost: 'Cost position',
    dbKpiBudget: 'WBS Budget',
    dbKpiActual: 'Cost Incurred',
    dbKpiBalance: 'Budget Balance',
    dbKpiConsumed: 'Budget Consumed',
    dbOverrunNodes: 'items running over budget',

    dbSecExposure: 'Commercial exposure',
    dbExposureNote:
      'Amounts the client has not yet admitted. Shown for review only — these are not earned revenue.',
    dbKpiExposure: 'Total Exposure',
    dbKpiVariationsPending: 'Variations Pending',
    dbKpiClaimsLive: 'Claims Live',
    dbKpiDisputes: 'In Dispute',
    dbKpiDisputesHint: 'Referred to conciliation or arbitration',
    dbKpiEotDays: 'EOT Days Claimable',

    dbSecHindrance: 'Delay days by responsibility',
    dbHindranceNote:
      'Client-attributable days are the basis of an extension of time claim, so this split matters more than the total.',
    dbOpenHindrances: 'Open Hindrances',
    dbHindranceDays: 'Open Delay Days',
    dbDays: 'days',
    dbEvents: 'events',
    dbNoHindrances: 'No delay events recorded',

    dbSecGuarantees: 'Guarantees',
    dbKpiBgLive: 'Guarantees Outstanding',
    dbKpiBgExpiring: 'Falling Due',
    dbBgLapsed: 'lapsed and not extended',

    dbSecReporting: 'Site reporting',
    dbKpiDprCount: 'Reports Filed',
    dbKpiDprPending: 'Awaiting Approval',
    dbLastReport: 'Last Report',
    dbNoReports: 'No daily reports filed',
    dbReportingGap: 'No report for',

    dbSecTrend: 'Daily output trend',
    dbTrendNote:
      'Executed quantity per daily progress report. A baseline programme is needed for a true S-curve.',
    dbNoTrend: 'Not enough reports to show a trend',

    dbEmpty: 'Select a project',
    dbEmptyHint: 'Choose a project to see its control position.',
    dbOpenRegister: 'Open register',

  },

  // ===========================================================================
  procurement: {
    purchaseRequisitions: 'Purchase Requisitions',
    purchaseRequisition: 'Purchase Requisition', // client may call this 'Indent'
    prShort: 'PR',
    rfq: 'RFQ / Enquiry', // client may call this 'Enquiry'
    vendorQuotations: 'Vendor Quotations', // client may call this 'Offers'
    quotationComparison: 'Quotation Comparison', // client may call this 'Comparative Statement'
    purchaseOrders: 'Purchase Orders',
    purchaseOrder: 'Purchase Order',
    poShort: 'PO',
    purchaseInvoiceCapture: 'Purchase Invoice Capture', // client may call this 'Bill Entry'

    requiredBy: 'Required By',
    indentedBy: 'Indented By',
    priority: 'Priority',
    justification: 'Justification',
    deliveryLocation: 'Delivery Location',
    deliverySchedule: 'Delivery Schedule',
    quotedRate: 'Quoted Rate',
    basicAmount: 'Basic Amount',
    discount: 'Discount',
    taxableAmount: 'Taxable Amount',
    cgst: 'CGST',
    sgst: 'SGST',
    igst: 'IGST',
    freight: 'Freight',
    poValue: 'PO Value',
    orderedQty: 'Ordered Quantity',
    receivedQty: 'Received Quantity',
    pendingQty: 'Pending Quantity',
    invoiceNo: 'Invoice No.',
    invoiceDate: 'Invoice Date',
    invoiceAmount: 'Invoice Amount',

    prFull: 'Purchase Requisition (Indent)',
    prSubtitle:
      'What site needs, when it is needed and why — the document every purchase order starts from.',
    prNew: 'New Requisition',
    prEdit: 'Edit Requisition',
    prEmpty: 'No requisitions raised',
    prEmptyHint: 'Site engineers raise an indent here when material is needed.',
    prNo: 'Indent No.',
    prDate: 'Indent Date',
    prLines: 'Materials Required',
    prItems: 'items',
    prEstimatedValue: 'Estimated Value',
    prEstimatedRate: 'Estimated Rate',
    prEstimatedNote:
      'Estimated rates are indicative only, so the approver can see the money involved. The rate on the purchase order comes from the quotation.',
    prOrderedQty: 'Ordered',
    prPendingQty: 'Yet to Order',
    prOrderStatus: 'Order Position',
    prNotOrdered: 'Not ordered',
    prPartlyOrdered: 'Partly ordered',
    prFullyOrdered: 'Fully ordered',
    prOverdue: 'Required date passed',
    prDaysToRequired: 'Required In',
    prDays: 'days',
    prRemarks: 'Remarks',
    prKpiTotal: 'Requisitions Raised',
    prKpiPending: 'Awaiting Approval',
    prKpiAwaitingOrder: 'Approved, Not Ordered',
    prKpiAwaitingOrderHint: 'Estimated value still to be placed on order',
    prKpiUrgent: 'Urgent or Emergency',
    prOverdueWarning: 'past the required date',
    prLinesRequired: 'Add at least one material line.',
    prJustificationRequired: 'Give a reason — an urgent indent needs one.',
    prRequiredBeforeDate: 'The required-by date cannot be before the indent date.',
    secPrHeader: 'Indent',
    secPrRequirement: 'Requirement',
    secPrLines: 'Materials',
    secPrNotes: 'Notes',
    prpNORMAL: 'Normal',
    prpURGENT: 'Urgent',
    prpEMERGENCY: 'Emergency',
    
    // --- RFQ / enquiry -----------------------------------------------------
    rfqFull: 'Request for Quotation',
    rfqSubtitle:
      'Enquiries floated to vendors against approved indents, and who has responded against each.',
    rfqNew: 'New Enquiry',
    rfqEdit: 'Edit Enquiry',
    rfqEmpty: 'No enquiries floated',
    rfqEmptyHint: 'Float an enquiry against an approved indent to start collecting offers.',
    rfqNo: 'Enquiry No.',
    rfqDate: 'Enquiry Date',
    rfqSubject: 'Subject',
    rfqDueDate: 'Quotations Due By',
    rfqValidity: 'Offer Validity (Days)',
    rfqDeliveryLocation: 'Delivery Location',
    rfqDeliverySchedule: 'Delivery Schedule',
    rfqPaymentExpected: 'Payment Terms Sought',
    rfqFreight: 'Freight Basis',
    rfqInspection: 'Inspection / Test Certificate Required',
    rfqScope: 'Scope & Conditions',
    rfqRemarks: 'Internal Remarks',
    rfqPreparedBy: 'Prepared By',
    rfqItems: 'Items',
    rfqLines: 'Items Enquired',
    rfqVendors: 'Vendors',
    rfqVendorsInvited: 'Vendors Invited',
    rfqResponses: 'Responses',
    rfqSentOn: 'Sent On',
    rfqMode: 'Sent By',
    rfqResponse: 'Response',
    rfqFromPr: 'From Indent',
    rfqPickPr: 'Pull Items from Indents',
    rfqPickPrHint: 'Approved indents awaiting an order. Pending quantities are pulled through.',
    rfqSourceIndents: 'Source Indents',
    rfqNoIndents: 'No approved indents awaiting an order for this project.',
    rfqEstimatedValue: 'Estimated Value',
    rfqEstimateNote:
      'The estimate is for internal sanction only and is not shown on the enquiry sent to vendors.',
    rfqOverdue: 'Closed for quoting',
    rfqDueIn: 'Due in',
    rfqDaysLeft: 'days',
    rfqClosingSoon: 'Closing soon',
    rfqUnderSubscribed: 'Below three offers',
    rfqUnderSubscribedHint: 'Fewer than three comparable offers — record a justification on the file.',
    rfqKpiFloated: 'Enquiries Floated',
    rfqKpiOpen: 'Open for Quoting',
    rfqKpiAwaiting: 'Offers Awaited',
    rfqKpiReceived: 'Offers Received',
    rfqClosingHint: 'Closing within three days',
    rfqThinHint: 'Enquiries with fewer than three offers',
    rfqSubjectRequired: 'Give the enquiry a short subject line.',
    rfqDueBeforeDate: 'The due date cannot be before the enquiry date.',
    rfqVendorRequired: 'Invite at least one vendor before floating the enquiry.',
    rfqLineRequired: 'Add at least one item to the enquiry.',
    secRfqHeader: 'Enquiry',
    secRfqItems: 'Items Enquired',
    secRfqTerms: 'Commercial Terms',
    secRfqVendors: 'Vendors Invited',
    rmEMAIL: 'Email',
    rmWHATSAPP: 'WhatsApp',
    rmCOURIER: 'Courier',
    rmHAND_DELIVERY: 'By Hand',
    rmPORTAL: 'Vendor Portal',
    rrAWAITED: 'Awaited',
    rrRECEIVED: 'Offer Received',
    rrREGRETTED: 'Regretted',
    rrNO_RESPONSE: 'No Response',
    ftFOR_SITE: 'FOR Site',
    ftEX_WORKS: 'Ex-Works',
    ftEXTRA_AT_ACTUALS: 'Freight Extra at Actuals',
    ftINCLUSIVE: 'All Inclusive',

        // --- Vendor quotations -------------------------------------------------
    qtnSubtitle:
      'Offers received against enquiries, recorded at landed cost so they can be compared honestly.',
    qtnNew: 'Record Offer',
    qtnEdit: 'Edit Offer',
    qtnEmpty: 'No offers recorded',
    qtnEmptyHint: 'Record an offer against a floated enquiry to build the comparison.',
    qtnNo: 'Offer No.',
    qtnDate: 'Offer Date',
    qtnRfq: 'Against Enquiry',
    qtnVendor: 'Vendor',
    qtnVendorRef: 'Vendor Reference No.',
    qtnVendorRefDate: 'Vendor Reference Date',
    qtnValidUntil: 'Valid Until',
    qtnReceivedOn: 'Received On',
    qtnPaymentTerms: 'Payment Terms Offered',
    qtnDeliveryDays: 'Delivery Period (Days)',
    qtnWarranty: 'Warranty / Testing',
    qtnDeviations: 'Deviations from Enquiry',
    qtnRemarks: 'Internal Remarks',
    qtnTechnical: 'Technically Qualified',
    qtnTechnicalHint: 'Scrutinise the offer technically before the rates are weighed.',
    qtnQualified: 'Qualified',
    qtnDisqualified: 'Not Qualified',
    qtnPendingScrutiny: 'Scrutiny Pending',
    qtnBasicValue: 'Basic Value',
    qtnCharges: 'Freight & Charges',
    qtnTax: 'GST',
    qtnLandedValue: 'Landed Value',
    qtnLandedRate: 'Landed Rate',
    qtnLandedNote:
      'Landed value adds freight, loading and packing quoted extra, plus GST. Two offers are comparable only at this figure.',
    qtnFreight: 'Freight',
    qtnLoading: 'Loading & Unloading',
    qtnPacking: 'Packing & Forwarding',
    qtnChargesGst: 'GST on Charges (%)',
    qtnBasicRate: 'Basic Rate',
    qtnMake: 'Make Offered',
    qtnNotQuoted: 'Not Quoted',
    qtnPartial: 'Partial offer',
    qtnPartialHint: 'One or more enquiry items not quoted.',
    qtnExpired: 'Validity lapsed',
    qtnExpiringSoon: 'Expiring soon',
    qtnLowest: 'Lowest landed',
    qtnPickRfq: 'Select the enquiry this offer answers',
    qtnPickVendor: 'Select the vendor',
    qtnRfqRequired: 'Select the enquiry this offer is against.',
    qtnVendorRequired: 'Select the vendor who sent the offer.',
    qtnLineRequired: 'Record at least one line.',
    qtnValidityBeforeDate: 'Validity cannot end before the offer date.',
    qtnKpiLive: 'Live Offers',
    qtnKpiQualified: 'Technically Qualified',
    qtnKpiPending: 'Scrutiny Pending',
    qtnKpiValue: 'Landed Value on Table',
    secQtnHeader: 'Offer',
    secQtnLines: 'Rates Quoted',
    secQtnCharges: 'Charges & Taxes',
    secQtnTerms: 'Commercial Terms',
    chINCLUDED: 'Included in Rate',
    chEXTRA: 'Extra',
    chNOT_APPLICABLE: 'Not Applicable',
  },

  // ===========================================================================
  inventory: {
    grn: 'Goods Receipt (GRN)', // client may call this 'MRN' or 'Material Receipt'
    grnShort: 'GRN',
    materialIssue: 'Material Issue', // client may call this 'Issue Slip'
    materialReturn: 'Material Return',
    stockTransfer: 'Stock Transfer',
    stockAdjustment: 'Stock Adjustment', // client may call this 'Physical Verification'
    stockSummary: 'Stock Summary',
    stockLedger: 'Stock Ledger',
    openingStock: 'Opening Stock',

    receivedFrom: 'Received From',
    challanNo: 'Supplier Challan No.',
    challanDate: 'Challan Date',
    vehicleNo: 'Vehicle No.',
    gateEntryNo: 'Gate Entry No.',
    challanQty: 'Challan Quantity',
    acceptedQty: 'Accepted Quantity',
    rejectedQty: 'Rejected Quantity',
    shortageQty: 'Shortage',
    issuedTo: 'Issued To',
    issuePurpose: 'Purpose',
    costCode: 'Cost Code',
    fromStore: 'From Store',
    toStore: 'To Store',
    stockInHand: 'Stock in Hand',
    stockValue: 'Stock Value',
    lastReceiptDate: 'Last Receipt Date',
    consumption: 'Consumption',
    inwardQty: 'Inward',
    outwardQty: 'Outward',
    closingQty: 'Closing',
  },

  // ===========================================================================
  subcontract: {
    workOrders: 'Work Orders', // client may call this 'Sub Contract' or 'Labour Order'
    workOrder: 'Work Order',
    woShort: 'WO',
    measurements: 'Measurements',
    measurementSheet: 'Measurement Sheet', // client may call this 'MB' (Measure Book)
    bills: 'Bills', // client may call this 'RA Bills'
    raBill: 'Running Account Bill',
    deductions: 'Deductions & Recovery',

    subcontractorName: 'Subcontractor Name',
    workDescription: 'Work Description',
    woValue: 'Work Order Value',
    agreedRate: 'Agreed Rate',
    measuredQty: 'Measured Quantity',
    cumulativeQty: 'Cumulative Quantity',
    previousQty: 'Previous Quantity',
    thisBillQty: 'This Bill Quantity',
    billNo: 'Bill No.',
    billAmount: 'Bill Amount',
    tds: 'TDS',
    retention: 'Retention',
    advanceRecovery: 'Advance Recovery',
    materialRecovery: 'Material Recovery',
    penalty: 'Penalty',
    netPayable: 'Net Payable',
    measuredBy: 'Measured By',
    checkedBy: 'Checked By',
  },

  // ===========================================================================
  plant: {
    equipmentRegister: 'Equipment Register',
    deployment: 'Deployment',
    logBook: 'Log Book',
    fuelIssue: 'Fuel Issue', // client may call this 'Diesel Issue'
    maintenance: 'Maintenance',
    breakdowns: 'Breakdowns',

    equipmentCode: 'Equipment Code',
    equipmentName: 'Equipment',
    equipmentType: 'Equipment Type',
    registrationNo: 'Registration No.',
    ownership: 'Ownership',
    owned: 'Owned',
    hired: 'Hired',
    hireVendor: 'Hire Vendor',
    hireRate: 'Hire Rate',
    operator: 'Operator',
    deployedAt: 'Deployed At',
    openingHmr: 'Opening HMR / KM',
    closingHmr: 'Closing HMR / KM',
    hoursWorked: 'Hours Worked',
    idleHours: 'Idle Hours',
    breakdownHours: 'Breakdown Hours',
    dieselIssued: 'Diesel Issued (Ltr)',
    avgConsumption: 'Average Consumption',
    maintenanceType: 'Maintenance Type',
    nextServiceDue: 'Next Service Due',
    breakdownReason: 'Breakdown Reason',
    downtime: 'Downtime',
    resolvedOn: 'Resolved On',
  },

  // ===========================================================================
  hr: {
    employees: 'Employees',
    attendance: 'Attendance',
    leave: 'Leave',
    payroll: 'Payroll',
    salaryAdvances: 'Salary Advances',
    expenseClaims: 'Expense Claims', // client may call this 'Reimbursement'
    labourAttendance: 'Labour Attendance', // client may call this 'Muster Roll'
    labourCompliance: 'Labour Compliance', // ESI / PF / licence tracking

    presentDays: 'Present Days',
    absentDays: 'Absent Days',
    overtimeHours: 'Overtime Hours',
    leaveType: 'Leave Type',
    leaveBalance: 'Leave Balance',
    grossSalary: 'Gross Salary',
    deduction: 'Deductions',
    netSalary: 'Net Salary',
    advanceAmount: 'Advance Amount',
    claimAmount: 'Claim Amount',
    expenseHead: 'Expense Head',
    gangSize: 'Gang Size',
    skilledCount: 'Skilled',
    unskilledCount: 'Unskilled',
    pfNumber: 'PF Number',
    esiNumber: 'ESI Number',
    licenceNo: 'Licence No.',
  },

  // ===========================================================================
    documents: {
    library: 'Document Library',
    librarySubtitle: 'Every file attached anywhere in the system — quotations, challans, licences and certificates.',
    upload: 'Upload',
    uploadSubtitle: 'Attach a file and link it to the vendor, subcontractor, equipment or document it belongs to.',
    expiryTracker: 'Expiry Tracker',
    expirySubtitle: 'Statutory documents that have expired or are due for renewal.',
    documentName: 'Document Name',
    documentType: 'Document Type',
    linkedTo: 'Linked To',
    linkedType: 'Linked Record Type',
    validFrom: 'Valid From',
    validTo: 'Valid To',
    daysToExpiry: 'Days to Expiry',
    expired: 'Expired',
    expiringSoon: 'Expiring Soon',
    valid: 'Valid',
    noExpiry: 'No expiry',
    expiredDaysAgo: 'Expired {days} days ago',
    expiresInDays: 'in {days} days',
    fileSize: 'Size',
    libraryEmpty: 'No documents found',
    libraryEmptyHint: 'Files attached to vendors, equipment, subcontractors and transactions appear here.',
    expiryEmpty: 'Nothing due for renewal',
    expiryEmptyHint: 'Documents approaching their expiry date will be listed here.',
    uploadEmpty: 'No file chosen yet',
    linkEntity: 'Attach To',
    linkRecord: 'Record',
    entDocuments: 'Transaction Document',
    entVendors: 'Vendor',
    entSubcontractors: 'Subcontractor',
    entEquipment: 'Equipment',
    entEmployees: 'Employee',
    entProjects: 'Project',
    entCompanies: 'Company',
    fileRequired: 'Choose a file to upload.',
    categoryRequired: 'Select a document type.',
    recordRequired: 'Select the record this document belongs to.',
    expiryBeforeValidFrom: 'Expiry date must be after the valid-from date.',
    withinDays: 'Due within',
    days30: '30 days',
    days60: '60 days',
    days90: '90 days',
    showExpired: 'Include expired',
    secFile: 'File',
    secClassify: 'Classification',
    secLink: 'Linked Record',
    secValidity: 'Validity',
    remarks: 'Remarks',
    uploadedBy: 'Uploaded By',
    uploadedOn: 'Uploaded On',
    deleteFile: 'Delete File',
    deleteWarning: 'This file will be removed from the record it is attached to.',
    kpiTracked: 'Tracked Documents',
    kpiExpired: 'Expired',
    kpiDueSoon: 'Due in 30 Days',
    kpiValid: 'Currently Valid',
    trackedHint: 'Documents that carry an expiry date',
    goToLibrary: 'Open Document Library',
    uploadAnother: 'Upload Another',
    uploadDone: 'File attached. It now appears in the Document Library.',
  },

  // ===========================================================================
  reports: {
    catalogue: 'Reports Catalogue',
    exportBatches: 'Export Batches',
    exportLog: 'Export Log',
    reportName: 'Report Name',
    module: 'Module',
    batchNo: 'Batch No.',
    exportedOn: 'Exported On',
    recordCount: 'Records',
  },

  // ===========================================================================
  admin: {
    users: 'Users',
    rolesPermissions: 'Roles & Permissions',
    approvalMatrix: 'Approval Matrix',
    numberSeries: 'Number Series',
    auditLog: 'Audit Log',
    vendorPortal: 'Vendor Portal',
    subcontractorPortal: 'Subcontractor Portal',
    userName: 'User Name',
    role: 'Role',
    lastLogin: 'Last Login',
    active: 'Active',
    inactive: 'Inactive',
    level: 'Level',
    approver: 'Approver',
    seriesPrefix: 'Prefix',
    nextNumber: 'Next Number',
  },

  // ===========================================================================
  status: {
    DRAFT: 'Draft',
    SUBMITTED: 'Submitted',
    PENDING_APPROVAL: 'Pending Approval',
    APPROVED: 'Approved',
    REJECTED: 'Rejected',
    RETURNED: 'Returned',
    REVISED: 'Revised',
    CANCELLED: 'Cancelled',
    CLOSED: 'Closed',
  },

  // ===========================================================================
  approval: {
    title: 'Approval Status',
    level: 'Level',
    approver: 'Approver',
    action: 'Action',
    actionedOn: 'Action Date',
    remarks: 'Remarks',
    waitingWith: 'Currently waiting with',
    notStarted: 'Not yet reached this level',
    pending: 'Awaiting action',
    completed: 'Approval completed',
    noWorkflow: 'This document does not require approval.',
  },

  // ===========================================================================
  audit: {
    title: 'Audit Trail',
    user: 'User',
    timestamp: 'Date & Time',
    action: 'Action',
    changes: 'Changed Fields',
    noEntries: 'No activity recorded yet',
    noEntriesHint: 'Every change made to this document will be listed here.',
    fieldChanged: 'changed from',
    fieldChangedTo: 'to',
  },

  // ===========================================================================
  detail: {
    tabDetails: 'Details',
    tabLineItems: 'Line Items',
    tabAttachments: 'Attachments',
    tabApprovals: 'Approvals',
    tabAudit: 'Audit Trail',
    summary: 'Summary',
  },

  // ===========================================================================
  importWizard: {
    title: 'Import from Excel',
    step1: 'Download Template',
    step2: 'Upload File',
    step3: 'Preview & Validate',
    step4: 'Confirm Import',
    step1Hint:
      'Download the Excel template, fill in your data and keep the column headings unchanged.',
    downloadTemplate: 'Download Template',
    step2Hint: 'Upload the filled template. Only .xlsx and .csv files are accepted.',
    step3Hint: 'Rows with errors are highlighted. Correct them in the file and upload again.',
    step4Hint: 'Confirm to import all valid rows. Rows with errors will be skipped.',
    rowNo: 'Row',
    validationError: 'Error',
    rowsValid: 'Rows ready to import',
    rowsFailed: 'Rows with errors',
    rowsImported: 'Rows imported',
    importComplete: 'Import completed',
    next: 'Next',
    back: 'Back',
    startImport: 'Start Import',
    done: 'Done',
  },

  // ===========================================================================
  home: {
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    contextLine: 'You are working in',
    waitingForMyAction: 'Waiting for my action',
    waitingForMyActionHint: 'Documents that cannot move forward until you approve or reject them.',
    nothingWaiting: 'Nothing is waiting for your action',
    nothingWaitingHint: 'Approvals assigned to you will appear here.',
    myPendingTasks: 'My pending tasks',
    myPendingTasksHint: 'Work you have started but not yet completed.',
    noPendingTasks: 'You are up to date',
    noPendingTasksHint: 'New tasks will appear here as work progresses.',
    alerts: 'Alerts',
    alertsHint: 'Items that need attention soon.',
    noAlerts: 'No alerts',
    noAlertsHint: 'Expiries, low stock and breakdowns will be flagged here.',
    quickCreate: 'Quick Create',
    newPr: 'New Purchase Requisition',
    newGrn: 'New GRN',
    newIssue: 'New Material Issue',
    newDpr: 'New DPR',
    newFuelIssue: 'New Fuel Issue',
    dprNotSubmitted: 'Daily Progress Report not submitted for today',
    draftsNotSubmitted: 'Draft documents not yet submitted',
    returnedForCorrection: 'Documents returned to you for correction',
    docsExpiring: 'Documents expiring within 30 days',
    lowStock: 'Items below reorder level',
    equipmentBreakdown: 'Equipment currently under breakdown',
    overdueMaintenance: 'Equipment with overdue maintenance',
    pendingCount: 'pending',
    openItem: 'Open',
    viewAll: 'View all',
  },

  // ===========================================================================
  login: {
    title: 'Sign in',
    subtitle: 'Enter your credentials to continue',
    email: 'Email',
    emailPlaceholder: 'name@company.co.in',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    signIn: 'Sign in',
    demoNotice:
      'Demonstration environment. Sign-in is not verified — any email and password will proceed.',
    rolePicker: 'Continue as',
    rolePickerHint:
      'Choose a role to see the application from that person’s point of view. The menu changes to match the role.',
    forgotPassword: 'Forgot password?',
        // --- Added: login brand panel & form states ---
    brandHeading: 'Enterprise Resource Planning',
    brandSubheading:
      'One system for projects, procurement, stores, subcontractors, plant and people.',
    brandPointProjects: 'Track project progress, budgets and daily site activity',
    brandPointProcurement: 'Control indents, purchase orders and material receipts',
    brandPointStores: 'Know exactly what stock is at every site store',
    brandPointVisibility: 'Give management one reliable view across all projects',
    emailRequired: 'Please enter your email address',
    passwordRequired: 'Please enter your password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    signingIn: 'Signing in…',
    viewAs: 'View the system as',
    supportNote: 'For access or password help, contact your system administrator.',
  },

  // ===========================================================================
  roles: {
    ADMINISTRATOR: 'Administrator',
    PROJECT_MANAGER: 'Project Manager',
    SITE_ENGINEER: 'Site Engineer',
    STORE_KEEPER: 'Store Keeper',
    PROCUREMENT_OFFICER: 'Procurement Officer',
    ACCOUNTS: 'Accounts',
    MANAGEMENT: 'Management',
    VENDOR: 'Vendor',
    SUBCONTRACTOR: 'Subcontractor',
  },

  // ===========================================================================
  // Plain-English explanations shown by HelpHint for first-time ERP users.
  help: {
    purchaseRequisition:
      'A written request from the site asking the purchase department to buy materials. It does not order anything by itself — it becomes a Purchase Order only after approval.',
    purchaseOrder:
      'The official order sent to a vendor confirming what you are buying, at what rate and by when. Once issued, the vendor can supply against it.',
    grn: 'Recorded when material physically arrives at the store. It confirms how much was actually received and accepted, which may be less than what was ordered.',
    materialIssue:
      'Records material going out of the store to a work location. This is what turns stored stock into project cost.',
    measurementSheet:
      'The record of work physically measured at site. Subcontractor bills are prepared from these measured quantities.',
    workOrder:
      'The agreement with a subcontractor for a defined scope of work at agreed rates, against which measurements and bills are raised.',
    dpr: 'A daily record of work done, manpower, equipment and weather at site. It is the base record for progress reporting.',
    wbs: 'A coded breakdown of the project into activities such as earthwork or subgrade, so that cost and progress can be tracked activity by activity.',
    approvalTimeline:
      'Shows who has to approve this document and in what order. The highlighted level is the person it is currently waiting with.',
    statusChip:
      'Shows where the document has reached in its workflow, from Draft through to Approved or Closed.',
    companyProjectContext:
      'You may work across more than one company and project. This shows which one you are currently working in — all records you create belong to it.',
    retention:
      'A percentage of the bill amount held back until the work is complete, released later as per contract terms.',
    tds: 'Tax deducted at source from the payable amount as required under the Income Tax Act.',
    uom: 'The unit a material is counted in. Cement is bought in bags but often stored in tonnes — recording both, with the conversion between them, keeps stock figures correct.',
    uomDecimals: 'How many digits after the decimal point are allowed. Bags are whole numbers, but diesel and concrete need three decimals.',

    hsn: 'The tax code printed on every purchase invoice. HSN codes classify goods, SAC codes classify services. The GST rate follows from the code, so getting it right here keeps every downstream invoice and Tally export correct.',
    hsnSplit: 'Within one state the tax splits into CGST and SGST, half each. Across states it is a single IGST at the full rate. The system fills all three from the GST rate you enter.',

    item: 'The master record for anything you buy, store or issue. Every purchase order, receipt and issue line points back to an item here, so the code and unit set here follow the material through the whole system.',
    itemType: 'Decides how the item behaves. Materials and consumables are bought and consumed. Returnable items such as shuttering are expected back. Produced items come out of your own plant. Services are not stocked at all.',
    itemUnits: 'Materials are often bought in one unit and stored in another. Cement is purchased in bags but tracked in tonnes. Recording the conversion factor keeps stock and purchase figures reconciled.',
    itemStock: 'Minimum and reorder levels drive the low-stock alerts on the home page. Lead time is how long the vendor typically takes, so the alert fires early enough to act.',
    itemValuation: 'How the value of stock on hand is calculated when material arrives at different rates. Weighted average is the common choice for construction materials.',

    vendor: 'The master record for anyone you buy from or hire. Purchase orders, receipts and bills all point back here, so the GSTIN and payment terms set here flow into every downstream document and the Tally export.',
    vendorGstin: 'Fifteen characters. The first two digits are the state code, the next ten are the PAN, and the rest identify the registration. The system checks all three agree, because a wrong GSTIN means the input tax credit is lost.',
    vendorMsme: 'Udyam registration number, if the vendor is a registered micro or small enterprise. Worth capturing because payments to MSME vendors carry a statutory time limit, and finance will need the flag at payment run.',
    vendorCreditDays: 'How many days after the invoice date payment falls due. Drives the payables ageing view and the overdue alerts.',
    subcontractor:
      'The agency that executes work at site. Work orders, measurement sheets and running account bills all point back to a record here, so the code set here follows the agency through the whole system.',
    labourLicence:
      'An agency supplying twenty or more workers needs a licence under the Contract Labour Act. Recording the licence number here lets the system flag it before it expires, which is what an audit or a client inspection asks for.',

    company:
      'The legal entity that signs the contract and raises the invoice. Projects, purchase orders and GST returns all roll up to a company, so the entity chosen here decides which books a transaction lands in.',
    companyCin:
      'The Corporate Identity Number issued by the Registrar of Companies. Incorporated entities have one; an unincorporated joint venture does not, which is why the field is not required for a JV.',
    department:
      'Departments decide who approves what. A purchase indent raised at site routes to Procurement, and a payment to Accounts, so the department set on an employee determines which queue their documents land in.',
    departmentHead:
      'The person accountable for the department. Approval rules can be written against the department head rather than a named person, so the workflow keeps working when the post changes hands.',
        employee:
      'The person who raises, approves or receives a document. The department decides which approval queue their documents enter, and the project decides which books the cost lands in.',
    employeeReporting:
      'The reporting line is used where an approval rule says "the raiser\'s manager" rather than a named person, so the workflow survives transfers and promotions.',
    employeeStatutory:
      'PF and ESI numbers are needed on statutory returns. Not every employee has both, so neither is mandatory here.',
        project:
      'The contract being executed. Every indent, purchase order, issue and bill carries a project, which is how cost is attributed and how a client bill is built. Getting the project list right is a precondition for everything downstream.',
    projectChainage:
      'Chainage marks distance along a linear work in kilometres and metres, so Km 24+000 means 24 kilometres and zero metres. Roads and pipelines are measured this way; a bridge or building is not, so the fields stay blank for those.',
    projectContractValue:
      'The awarded contract value, stored in rupees and shown in crore. Variations and escalation are handled as separate documents rather than by editing this figure.',
        site:
      'The physical location a document happens at. A goods receipt lands at a store, an issue leaves one, and stock is counted per location — so the site list decides where stock can exist at all.',
    siteStock:
      'Only locations that hold stock appear in receipt, issue and transfer screens. A site office is a place people work, not a place material sits, so it is excluded.',
        equipment:
      'Every fuel issue, log book entry and maintenance job posts against an equipment record, so the code here becomes the cost centre for plant expenditure.',
    equipmentHire:
      'Hired plant is billed per hour or per day against a vendor. The rate recorded here is the reference the hire bill is checked against.',
    equipmentReading:
      'Plant is measured in running hours and vehicles in kilometres. Both are held in one field, so the service due figure must be read in the same unit as the current reading.',
    wbsBudget:
      'Budget is normally entered at the lowest level of the tree, because a parent total is the sum of its children. Entering both invites the two disagreeing.',
    documentExpiry: 'Statutory documents such as GST certificates, labour licences, insurance and fitness certificates carry a renewal date. The tracker lists them before they lapse.',
    documentLink: 'Every file belongs to a record — a vendor, a subcontractor, a machine or a transaction. Linking it here is what makes it findable later.',

    hindrance:
      'A record of anything that held up work — land not handed over, drawings awaited, utilities not shifted, rain. Kept day by day, it becomes the evidence for an extension of time.',
    eot: 'Extension of time. Where a delay is the client’s responsibility or beyond anyone’s control, the contract period can be extended so that delay damages do not apply.',
    variation:
      'Work that differs from the agreement — an extra item, a change in quantity, or a design revision. It is recorded, priced and put to the client, who may admit all, part or none of it. Keeping the claimed and admitted figures apart is what makes the final account defensible.',
    deviationLimit:
      'Most Indian contracts allow quantities to move within a stated band, often 25 per cent, at the agreement rate. Beyond that band, or for an item not in the agreement at all, a fresh rate has to be worked out and approved before payment.',
    claim:
      'A request to the client for more time or more money because of something that went wrong — land handed over late, drawings held up, prices moved. It is not the same as a variation, which prices a change in the work itself.',
    claimNotice:
      'Most contracts require the client to be told within a fixed period, often twenty-eight days, that a claim is coming. Miss that window and the entitlement can be lost however good the underlying case is, which is why the notice date is recorded separately from the detailed particulars.',
    contractPosition:
    'The contract statement starts from the agreement value, adds what the client has formally admitted, and shows separately what is still being pursued. Only the revised contract value is a defensible figure — the anticipated value assumes every pending variation and claim succeeds in full, which rarely happens.',
    bankGuarantee:
      'A bank guarantee is the bank’s undertaking to pay the client if the contractor defaults. It locks up margin money or an FDR and carries commission every quarter, so a guarantee left running after the obligation ends costs real money. The greater risk is the other way: if validity lapses before the client releases it, the client can call for invocation. Extensions are normally applied for about two months ahead.',
    projectDashboard:
      'This is the monthly review position. Physical progress is judged against time elapsed: if 60% of the period has gone but only 45% of the work is done, the project is slipping by 15 points and the reason should show up in the hindrance register. The exposure figures are money the client has not yet admitted, so they are a watch list, not revenue.',
    rfq:
      'An enquiry sent to several vendors for the same items, so their offers can be compared on equal terms. It carries the quantity, the delivery point, the payment terms sought and the last date for quotations — but never a rate. Three comparable offers is the working norm; fewer needs a justification on the purchase file.',
    quotation:
      'A vendor offer recorded against an enquiry. The rate on the letterhead is rarely the whole story — freight, loading and packing are often quoted extra, and GST sits on top. This screen records all of it and works out the landed cost, which is the only figure on which two offers may fairly be compared.',

  },
} as const;

export type Terminology = typeof terminology;
export type StatusKey = keyof typeof terminology.status;
export type RoleKey = keyof typeof terminology.roles;

export const t = terminology;
export default terminology;
